// Generated by LiveScript 1.2.0
(function(){
  var ref$, lines, unlines, getRaw, replacer, processReplacement, replace, slice$ = [].slice;
  ref$ = require('prelude-ls'), lines = ref$.lines, unlines = ref$.unlines;
  getRaw = function(input, node){
    var ref$, ref1$, startLine, startCol, endLine, endCol, area, areaLast;
    ref$ = node.loc, ref1$ = ref$.start, startLine = ref1$.line, startCol = ref1$.column, ref1$ = ref$.end, endLine = ref1$.line, endCol = ref1$.column;
    area = input.slice(startLine - 1, endLine);
    area[0] = area[0].slice(startCol);
    areaLast = area[area.length - 1];
    area[area.length - 1] = areaLast.slice(0, startLine === endLine ? endCol - startCol : endCol);
    return unlines(area);
  };
  replacer = function(input, node, queryEngine){
    return function(arg$, selector){
      var results, that;
      results = queryEngine.query(selector, node);
      if (that = results[0]) {
        return getRaw(input, that);
      } else {
        return '';
      }
    };
  };
  processReplacement = function(replacement, input, node, queryEngine){
    return replacement.replace(/\\n/g, '\n').replace(/{{}}/g, getRaw(input, node)).replace(/{{((?:[^}]|}[^}])+)}}/g, replacer(input, node, queryEngine));
  };
  replace = function(replacement, input, nodes, queryEngine){
    var origInputLines, inputLines, colOffset, lineOffset, lastLine, i$, len$, node, ref$, start, end, startLineNum, endLineNum, numberOfLines, startCol, endCol, replaceLines, startLine, endLine, startContext, endContext, replaceLast, endLen;
    origInputLines = lines(input);
    inputLines = origInputLines.slice(0);
    colOffset = 0;
    lineOffset = 0;
    lastLine = null;
    for (i$ = 0, len$ = nodes.length; i$ < len$; ++i$) {
      node = nodes[i$];
      ref$ = node.loc, start = ref$.start, end = ref$.end;
      startLineNum = start.line - 1 + lineOffset;
      endLineNum = end.line - 1 + lineOffset;
      numberOfLines = endLineNum - startLineNum + 1;
      colOffset = lastLine === startLineNum ? colOffset : 0;
      startCol = start.column + colOffset;
      endCol = end.column + (startLineNum === endLineNum ? colOffset : 0);
      replaceLines = lines(processReplacement(replacement, origInputLines, node, queryEngine));
      startLine = inputLines[startLineNum];
      endLine = inputLines[endLineNum];
      startContext = startLine.slice(0, startCol);
      endContext = endLine.slice(endCol);
      replaceLines[0] = startContext + "" + replaceLines[0];
      replaceLast = replaceLines[replaceLines.length - 1];
      endLen = replaceLast.length;
      replaceLines[replaceLines.length - 1] = replaceLast + "" + endContext;
      inputLines.splice.apply(inputLines, [startLineNum, numberOfLines].concat(slice$.call(replaceLines)));
      lineOffset += replaceLines.length - numberOfLines;
      colOffset = endLen - endCol;
      lastLine = endLineNum + lineOffset;
    }
    return unlines(inputLines).replace(/\n$/, '');
  };
  module.exports = {
    replace: replace
  };
}).call(this);
